"""Deterministic ATS Scoring Engine (spec Phase 7).

Transforms Requirement + Matching + Evidence into a deterministic,
explainable, versioned ATS Alignment score. Never generated by an LLM.
"""

from app.modules.scoring.config import ALGORITHM_VERSION, ScoringConfig, get_scoring_config
from app.modules.scoring.schemas import CategoryScoreResult, RequirementScoreResult, ScoreBreakdown, ScoringCategory
from app.modules.scoring.service import ScoringService

__all__ = [
    "ScoringConfig",
    "get_scoring_config",
    "ALGORITHM_VERSION",
    "ScoringService",
    "ScoreBreakdown",
    "ScoringCategory",
    "CategoryScoreResult",
    "RequirementScoreResult",
]
